version: "3"
services:
  food-recipe-react-app:
    #-it flag (for older versions of react)
    # stdin_open: true
    # tty: true

    #Build from current directory
    build:
      context: .
      dockerfile: Dockerfile.prod
      
    #ports
    ports:
      - "3000:80"

    #Bind mount
    # volumes:
    #   - "./src:/app/src"
    
    #Environment variables
    env_file:
      - ".env"